### ISSUE TITLE
When i set the mode as test or inference, server said:AttributeError: Can't get attribute 'Emotic' on <module '__main__' from 'main.py'>?How to solve this problem?

### ISSUE THREAD

**Issue by RyanShun-511** [Tandon-A/emotic#12]
when the command is 'python main.py --mode inference --inference_file .....'   and 'python main.py --mode test --inference_file ....’. There is a problem,said:**AttributeError: Can't get attribute 'Emotic' on <module '__main__' from 'main.py'>**.How can i solve this problem

**Comment by RyanShun-511** [comment]
add "from emotic import Emotic" in main.py.
I have solved this problem by this way.

**Comment by Tandon-A** [comment]
@RyanShun-511 
Hello, 

Thanks for the fix. I will update the code. 

Regards, 
Abhishek
