### ISSUE TITLE
About Projects

### ISSUE THREAD

**Issue by zhanglina94** [Tandon-A/emotic#16]
您好，最近在学习相关知识，请问融合然后网络发生变化了吗？修改的主要部分是什么呢?期待您的回答，谢谢。

**Comment by Tandon-A** [comment]
@zhanglina94 

Hello, 

I don't completely understand your question. Please elaborate. 

The fusion network is composed of two Fully Connected layers. This combines the features from the context and the body models and then generates the results in both continuous and discrete categories. You can take a look at the fusion model implementation [here](https://github.com/Tandon-A/emotic/blob/master/emotic.py). I would also suggest reading the [Emotic paper](https://arxiv.org/pdf/2003.13401.pdf). 

Please let me know if I have missed something. 

Thanks, 
Abhishek 

Below is the response on using Google Translate. My apologies if the translation has come out to be incorrect. 

------------------------------------------------------

以下是使用谷歌翻译的回复。 如果翻译结果不正确，我深表歉意。

你好，

我不完全理解你的问题。 请详细说明。

融合网络由两个全连接层组成。 这结合了上下文和身体模型的特征，然后生成连续和离散类别的结果。 您可以查看融合模型的实现 [这里](https://github.com/Tandon-A/emotic/blob/master/emotic.py)。 我还建议阅读 [Emotic paper](https://arxiv.org/pdf/2003.13401.pdf)。

如果我错过了什么，请告诉我。

谢谢，
阿布舍克

**Comment by zhanglina94** [comment]
Thank you very much for your answer!^-^
