### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by xiehou-design** [Tandon-A/emotic#19]
The link you shared with Google Drive has expired, can you share it again? Thank you.

**Comment by Tandon-A** [comment]
@xiehou-design 

Hello, 

Thank you for showing interest in my work. 

Emotic authors had changed the dataset access some time back and so the drive link has expired. 

The Emotic dataset can now be used only for non-commercial research and education purposes. 
Please, fill out the following form to request access to the dataset and the corresponding annotations.
[Access Request for EMOTIC](https://forms.gle/wvhComeDHwQPD6TE6)

I will also update this information in my repository. 

Regards, 
Abhishek

**Comment by xiehou-design** [comment]
> @xiehou-design
> 
> Hello,
> 
> Thank you for showing interest in my work.
> 
> Emotic authors had changed the dataset access some time back and so the drive link has expired.
> 
> The Emotic dataset can now be used only for non-commercial research and education purposes. Please, fill out the following form to request access to the dataset and the corresponding annotations. [Access Request for EMOTIC](https://forms.gle/wvhComeDHwQPD6TE6)
> 
> I will also update this information in my repository.
> 
> Regards, Abhishek

Thank you for your reply. I have obtained the data set.
