### ISSUE TITLE
How to test on pictures or videos

### ISSUE THREAD

**Issue by fyhfyhfyh123456** [Tandon-A/emotic#24]
How to test on pictures or videos, follow the steps to get the final result of a txt file.Thanks!

**Comment by Tandon-A** [comment]
To perform inference: 

```
> python main.py --mode inference --inference_file proj/debug_exp/inference_file.txt --experiment_path proj/debug_exp
```
* mode: Mode to run the main file.
* inference_file: Text file specifying images to perform inference. A row is: 'full_path_of_image x1 y1 x2 y2', where (x1,y1) and (x2,y2) specify the bounding box. Refer [sample_inference_list.txt](https://github.com/Tandon-A/emotic/blob/master/sample_inference_list.txt).
* experiment_path: Path of the experiment directory. Models stored in the the directory are used for inference.

**Comment by Tandon-A** [comment]
For video you can use[ yolo_inference.py](https://github.com/Tandon-A/emotic/blob/master/yolo_inference.py).
