### ISSUE TITLE
(x1,y1) and (x2,y2) the bounding box 

### ISSUE THREAD

**Issue by fyhfyhfyh123456** [Tandon-A/emotic#25]
How do inference_file.txt get，the sample-inference_file.txt file given in the project? Also, (x1,y1) and (x2,y2) specify where the bounding box comes from? Thank you so much!

**Comment by Tandon-A** [comment]
The sample_inference_file.txt gives an idea of how to structure the inference file. A row is: 'full_path_of_image x1 y1 x2 y2', where (x1,y1) and (x2,y2) specify the bounding box. 

In case you don't have the bounding box values for your images, you can run yolo_inference.py, which will first run a yolo model to obtain bounding box values and then run emotic on that. 

Note that it uses a yolo v3, which is now rather old.
