### ISSUE TITLE
Can you share your pretrained model?

### ISSUE THREAD

**Issue by congvm-it** [Tandon-A/emotic#3]
@Tandon-A Can you share your pre-trained model?

**Comment by congvm-it** [comment]
I've already found the author repo.
It seems very hard to reproduce the author's performance.
Are you working on this task?

**Comment by Tandon-A** [comment]
@congvm-it 

Hello, 

I agree with you that it is very hard to reproduce the author's performance. I refer you to the earlier issue, [#1](https://github.com/Tandon-A/emotic/issues/1), where I have mentioned a few things which improved the performance a bit. I don't have the model saved as of now and would require some time to retrain it. 

I was working on some more techniques to improve the results but got involved in different things and the project is on pause right now. 

Regards, 
Abhishek

**Comment by Tandon-A** [comment]
I have updated the readme with the link for the model weights. 

You can download them from [here](https://drive.google.com/drive/folders/1e-JLA7V73CQD5pjTFCSWnKCmB0gCpV1D?usp=sharing).
