### ISSUE TITLE
How could I get the emotic datasets?

### ISSUE THREAD

**Issue by SiriusQQY** [Tandon-A/emotic#30]
How could I get the emotic datasets?

**Comment by Tandon-A** [comment]
@SiriusQQY , 

Please follow the instructions from [here](https://github.com/Tandon-A/emotic?tab=readme-ov-file#emotic-dataset).

**Comment by SiriusQQY** [comment]
Sorry, I didn’t find the instructions

**Comment by Tandon-A** [comment]
Please fill the access form at this link ([https://forms.gle/wvhComeDHwQPD6TE6](https://forms.gle/wvhComeDHwQPD6TE6))
