### ISSUE TITLE
Problem with inference

### ISSUE THREAD

**Issue by ratkhohieu** [Tandon-A/emotic#4]
Hello,
I have a question about the threshold which you used. 
First, I try to calculate thresholds where precision is equal to recall. After that, results from model will compare with it to become array [1, 0, ...0]. If I continue with it and use the function "average_precision_score", I will get another meanAP.
Did I do any wrong steps?

**Comment by Tandon-A** [comment]
@ratkhohieu 
Hello, 

Thank you for showing interest in my work. 

The mean AP (computed over the test set) is a metric to assess the trained model's performance and compare it with other models. During testing, we first calculate the model outputs over the test set and then pass the ground truth labels along with the model outputs to the average_precision_score function.
At inference time, we use the calculated thresholds to convert the model output over an image to get the final categorical predictions. The thresholds calculation part and the conversion from confidence scores to categorical predictions is as you have mentioned. At inference time, technically, you wouldn't have access to the ground truth labels and wouldn't be able to call the average_precision_score. 

I hope this clarifies your doubt. 

Regards, 
Abhishek

**Comment by ratkhohieu** [comment]
Hello,
Thank you for replying to me.

Sorry, but it is not my point. I mean, I try to predict the final label (using threshold) of the test set ([1, 0, ..] form) and compute the mean AP. It is different from my result when I use probabilities from out of the model.

1. Probabilities->threshold->mAP
2. Probabilities->mAP

I don't know why it is different. average_precision_score has noted that "This implementation is not interpolated and is different from computing the area under the precision-recall curve with the trapezoidal rule". So maybe calculate thresholds, where precision is equal to recall will make different results?

**Comment by ratkhohieu** [comment]
Thank you for the very detailed explanation. It's my fault for not reading the metric carefully.  I got this point.
