### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'model/results/val_thresholds.npy'

### ISSUE THREAD

**Issue by ksra7900** [Tandon-A/emotic#5]
how can i fix this error???

**Comment by Tandon-A** [comment]
@ksra7900 

Hello, 

Please provide more information so that I can debug the issue and help you. Can you tell me the steps you performed? Please also share a snapshot (or list down the contents) of the 'model' folder and the 'model/results' folder. 

Regards, 
Abhishek

**Comment by ksra7900** [comment]
I download trained model and set path 
when I run python file, show this error 
I checking 'model/result' file , this file (val_thresholds.npy) doesn't extracted from trained model
![Screenshot from 2021-04-06 09-40-12](https://user-images.githubusercontent.com/81849499/113661901-3d378980-96bc-11eb-8302-6086354f740a.png)

**Comment by ksra7900** [comment]
??????

**Comment by Tandon-A** [comment]
The val_thresholds file is generated by the code during the training process. Once the training process is completed, the model is tested on the validation set. The thresholds calculated in this step are then saved to the npy file. 

You are receiving this error since you are directly running the inference code. 

I don't have the file and would require some time to retrain the models and prepare the same. 

Regards
Abhishek

**Comment by ksra7900** [comment]
okay
thank you Mr Abhishek

**Comment by ksra7900** [comment]
I training model and create val_thresholds.npy file
but, I have new problem
when system has loading 'model_emotic1.pth' file, get this error:
AttributeError: Can't get attribute 'Emotic' on <module '__main__' from '/home/amir/emotic/model/untitled0.py'>
whats the problem?
I using your trained model and code ???

**Comment by Tandon-A** [comment]
Hi, 

I have prepared the val_thresholds.npy file. You can download the [drive folder](https://drive.google.com/drive/folders/1e-JLA7V73CQD5pjTFCSWnKCmB0gCpV1D?usp=sharing) again. 

Can you share the untitled0.py file? It is not a part of the repository code. Looks like a custom file you have prepared. From the error, it seems that you are not importing the model class correctly. 

Regards,
Abhishek

**Comment by ksra7900** [comment]
'untitled0.py' is testing file
this error arises bring when I run main.py

**Comment by ksra7900** [comment]
'untitled0.py' is testing file
this error arises when I run main.py
![Screenshot from 2021-04-08 13-09-10](https://user-images.githubusercontent.com/81849499/113995722-bfb27b80-986b-11eb-9162-8124166788e0.png)

**Comment by Tandon-A** [comment]
Import the Emotic model in the inference file and it should work. Do let me know your results. 

Include the below line in the imports: 
`
from emotic import Emotic
`

**Comment by ksra7900** [comment]
New Error :(
how to get image address ???
![Screenshot from 2021-04-08 14-12-48](https://user-images.githubusercontent.com/81849499/114005465-cee9f700-9874-11eb-8fe8-69fcc2efbb68.png)

**Comment by Tandon-A** [comment]
You are using the sample_inference_list.txt, below are the contents:
/data/emotic19/emotic/mscoco/images/COCO_val2014_000000562243.jpg 86 58 564 628
/data/emotic19/emotic/mscoco/images/COCO_train2014_000000288841.jpg 485 149 605 473

The code will process each line. The code will try to read the image at the paths specified. Can you confirm if the images are available at the paths? You would need to change the paths according to your directory structure. I had added the sample_inference_list.txt file to give an idea as to how to develop the same.

**Comment by ksra7900** [comment]
Thanks a lot 
I can get result

**Comment by missyun125** [comment]
@ksra7900 I can't download EMOTIC dataset on the official website. Can you send the dataset to my email（604133530@qq.com）?
