### ISSUE TITLE
Can this model get the result like the gif you give or real time video?

### ISSUE THREAD

**Issue by Chen-yuiyui** [Tandon-A/emotic#6]
I want to know how fast this model is used to process the camera in real time？

**Comment by Tandon-A** [comment]
@Chen-yuiyui 

Hello, 

Apologies for the late reply. 

The models are fast. You can process a video (run person detection using Yolo v3, emotion recognition using Emotic, drawing the box on the person, and putting emotion annotations on each frame) at about 15 FPS on an Nvidia GeForce GTX 1650 Ti Mobile GPU. The speed reduces to about 3 FPS on an Intel i7 (10th gen) CPU. On Google Colab (with GPU) the speed is at about 11 FPS. 

Regards, 
Abhishek

**Comment by rashmi-learning** [comment]
@Tandon-A, could you please share the inference script?  How to integrate the Emotic model with the Yolo model. That will be really helpful.
Thank You
