### ISSUE TITLE
Why I got low mAP comparing with that in paper?

### ISSUE THREAD

**Issue by YHDASHEN** [Tandon-A/emotic#8]
Hi,
I ran the training step and got the models, then I ran test and the mAP was only 0.20610. 
Firstly, I thought maybe it's because of my bad training. So I downloaded [given trained models and thresholds](https://drive.google.com/drive/folders/1e-JLA7V73CQD5pjTFCSWnKCmB0gCpV1D) and the mAP of test step is still low. 
Then I thought about preprocessing step of dataset, I received errors like: `libpng warning: iCCP: known incorrect sRGB profile`, `libpng warning: iCCP: extra compressed data` and `Corrupt JPEG data: 44 extraneous bytes before marker 0xd9`, I don't know whether they have some bad influence.
Then I saw the result of test step from this [notebook](https://github.com/Tandon-A/emotic/blob/master/Colab_train_emotic.ipynb). It looks similar to my result. But I wonder why mAP is quite different from that in paper.
I'd appreciate if you could give me some hints.

Best regards,
Hui

**Comment by Tandon-A** [comment]
@YHDASHEN 

Hello, 

I agree with you that it is very hard to reproduce the author's performance. I refer you to the earlier issue, [#1](https://github.com/Tandon-A/emotic/issues/1), where I have mentioned a few things which improved the performance a bit. I was able to achieve the performance of 26.02 mAP using the strategies listed there. 

One more thing that worked for me was to set the pixels of the person to zero in the context image. This way the network was forced to look at other areas in the context image. 

You can try these approaches and that would surely boost the results. 

There were some corrupted images in the dataset which were failing the preprocessing, so when such errors came, I think, the code automatically skips them. 

Best Regards, 
Abhishek

**Comment by YHDASHEN** [comment]
Hi Abhishek,

thank you so much for your reply. I'll look into it.

Best regards,
Hui
